### ISSUE TITLE
Crash with Replay Mod

### ISSUE THREAD

**Issue by jwaxy** [PouekDEV/CList#12]
I joined a multiplayer server, played a bit then disconnected from it the replay mod saved the replay then I selected and tried to load it from replay mod's menu it said joining the world... then the game crashed.

This was my first time using Replay Mod so I know nothing about it. And first time for your mod too. I was searching for a client-side waypoint mod and only found bloated minimap mods that I didn't wanted but your mod was awesome It's what I wanted!

Thank you for this wonderful mod and can you please help me?

The crash log: https://mclo.gs/u5AFC30

**Comment by PouekDEV** [comment]
It seems, my mod crashed your game. I've never used Replay Mod, but the issue seems related to how Replay Mod handles the replaying part. It tricked my mod that you were joining a server but the server name was null so it crashed while searching for the save file. I'll try my best to find a solution but in the worst-case scenario, my mod is going to be labeled as incompatible with the replay mod. For now, I suggest not using the Replay Mod or CList.

**Comment by jwaxy** [comment]
Thank you for your fast reply! 😄 I wasn't using Replay Mod normally, I just wanted to try it. So it's not essential for me but thanks for looking into the issue.

**Comment by PouekDEV** [comment]
After thinking for a bit and searching the internet, I found info about another similar mod to mine (VoxelMap) having issues with getting world data while watching replays. Of course, VoxelMap wasn't crashing like my mod. I implemented a simple try-catch fix that eliminates crashes but doesn't load the waypoints. The fix will be in the next update.
