### ISSUE TITLE
Waypoint rendering locked to tickrate

### ISSUE THREAD

**Issue by minusHysteria** [PouekDEV/CList#21]
It appears that the rendering of the waypoints is locked to the tickrate of the client/server this may not be inherently bad but at higher fps the waypoints are extremely jarring and messy when the player is moving around.
Locking the fps to 20 perfectly syncs the waypoint rendering interval to the framerate, so I believe it to be tickrate dependent. 
Is there any way to resolve this within the mod itself?

**Comment by PouekDEV** [comment]
Thank you for reporting this issue!
After looking through my code for several days, banging my head on the wall, and getting help from the official Fabric server I finally found the issue. I used the player's position, which is not updated frequently, instead of the camera's in one function. Replacing it with the camera's position solved the issue and the fix will be available in the next update!
