### ISSUE TITLE
Guest doesn't save the list

### ISSUE THREAD

**Issue by AdamBrezik** [PouekDEV/CList#34]
Hi, we're playing on a home LAN and _single player / host machine_ saves the CList fine, but the guest machine sometimes seems to save the config only for the timespan of one server uptime? Not entirely sure, it just seems the values are saved and then we go play again and it's empty. Any ideas?

**Comment by PouekDEV** [comment]
Hi!
CList is working fine. You mentioned that you're playing on LAN, the issue here is that the host machine is always starting the game on a different port which to CList looks like another server. The solution here is to always start your local game on the same port. If that doesn't solve the problem, it means that your host machine is changing its local IP address. In that case, you can just assign the host machine the same local IP every time in your router settings or in the system settings. I hope that helps.

**Comment by AdamBrezik** [comment]
Thank you for your quick thinking and the clarification! I didn't realize this could be the cause.
