### ISSUE TITLE
CList crashed in 1.21 as soon as I wanted to make a waypoint

### ISSUE THREAD

**Issue by NextRaven10** [PouekDEV/CList#35]
As the title says

Crashlog: https://mclo.gs/UQrjZ4U

**Comment by PouekDEV** [comment]
I have looked at the crash log and to be fair it doesn't make any sense. I think there must be a mod that interferes with CList and that's why it crashed. After downloading the mods that were listed in the crash log, the only thing that was broken were the HSV sliders. If you could provide a full list including libraries that you use on a chance I missed something, we could get to the bottom of this issue.

**Comment by PouekDEV** [comment]
I am certain that I found the issue that was causing this. Because of the locale, the separator for the numbers wasn't a dot but a comma. It is now fixed.
